# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Creator Crew
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Team names, titles and social links
people:
  - name: Noodles
    pic: 1
    position: Server Owner
    social:
      - title: twitter
        url: https://twitter.com/BaggyNoodleArms
      - title: twitch
        url: https://www.twitch.tv/baggynoodlearms
      - title: instagram
        url: https://instagram.com/baggynoodlearms

  - name: MusiChele
    pic: 2
    position: Mod
    social:
      - title: twitch
        url: https://www.twitch.tv/musichele

  - name: BrockintheBox
    pic: 3
    position: Mod
    social:
      - title: twitch
        url: https://www.twitch.tv/misadventuresidr
      - title: instagram
        url: https://instagram.com/brockinthebox
      - title: youtube
        url: https://www.youtube.com/channel/UC9mYXoNYcSiylbY_sMObR8g

  - name: TheRealDarthGuy
    pic: 4
    position: Mod
    social:
      - title: twitch
        url: https://www.twitch.tv/therealdarthguy
      - title: twitter
        url: https://twitter.com/TheRealDarthGuy
      - title: instagram
        url: https://instagram.com/therealdarthguy
      - title: youtube
        url: https://www.youtube.com/channel/UCXO5RGKQrR1biEXfUFm9k6w
      - title: facebook
        url: https://facebook.com/therealdarthguy

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/TheTwitchCrew
  - title: facebook
    url: https://www.facebook.com/twitchcrew/
  - title: instagram
    url: https://www.instagram.com/twitchcrew/
  - title: twitch
    url: https://www.twitch.tv/twitchcrewcommunity/videos
  - title: youtube
    url: https://www.youtube.com/channel/UC19ux9oGaHJE2hpVJyZSKfw

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
